# Generated by Django 5.1.5 on 2025-02-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULL_NAME', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE_NUMBER', models.CharField(max_length=20)),
                ('DATE_OF_BIRTH', models.DateField()),
                ('ADDRESS', models.TextField()),
                ('PREVIOUS_ISLAMIC_EDUCATION', models.TextField(blank=True, null=True)),
                ('COURSE_CHOICE', models.CharField(choices=[('fiqh_hadith', 'Fiqh & Hadith (Compulsory)'), ('quran', 'Quran (Optional)'), ('tarbiya', 'Tarbiya (Optional)'), ('tahdid', 'Tahdid (Optional)')], default='fiqh_hadith', max_length=20)),
                ('CLASS_CATEGORY', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
            ],
        ),
    ]
