# Generated by Django 5.1.5 on 2025-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('courses', models.CharField(choices=[('fiqh_hadith', 'Fiqh & Hadith (Compulsory)'), ('quran', 'Quran (Optional)'), ('tarbiya', 'Tarbiya (Optional)'), ('tahid', 'Tahid (Optional)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
