# Generated by Django 5.1.5 on 2025-02-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_application_delete_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
